In [15]:
import pandas as pd

In [115]:
# Lectura y Verificación Estructural
df_urgencias = pd.read_csv("urgencias_hospitales.csv")

In [116]:
# Selección Simple y Proyección Múltiple
# serie_nivel_triage = df_urgencias["Nivel_Triage"]
vista_tabular = df_urgencias[["Hospital", "Especialidad", "Tiempo_Espera_Min"]]
vista_tabular

                  Hospital      Especialidad  Tiempo_Espera_Min
0        Hospital Infantil  Medicina Interna               90.0
1      Hospital San Isidro           Cirugía               45.0
2       Clínica San Marcel         Pediatría               60.0
3     Hospital Santa Sofía         Pediatría                NaN
4      Hospital San Isidro     Traumatología               60.0
...                    ...               ...                ...
1005    Clínica San Marcel         Pediatría               60.0
1006    Clínica San Marcel           Cirugía              120.0
1007    Clínica San Marcel         Pediatría               25.0
1008     Hospital Infantil         Pediatría               60.0
1009     Hospital Infantil           Cirugía               25.0

[1010 rows x 3 columns]

In [73]:
# Acceso por Etiqueta de Índice (loc)
df_urgencias.loc[75]

ID_Admision                     ADM-3076
Hospital               Hospital Infantil
Nivel_Triage                  Triage III
Especialidad                   Pediatría
Tiempo_Espera_Min                   10.0
Costo_Procedimiento             120000.0
Edad_Paciente                         10
Destino_Alta             Hospitalización
Name: 75, dtype: object

In [52]:
# Tratamiento de Redundancias
df_urgencias.drop_duplicates()

,ID_Admision,Hospital,Nivel_Triage,Especialidad,Tiempo_Espera_Min,Costo_Procedimiento,Edad_Paciente,Destino_Alta
0,ADM-3001,Hospital Infantil,Triage II,Medicina Interna,90.0,350000.0,29,Domicilio
1,ADM-3002,Hospital San Isidro,Triage II,Cirugía,45.0,NaN,9,Hospitalización
2,ADM-3003,Clínica San Marcel,Triage IV,Pediatría,60.0,120000.0,67,Domicilio
3,ADM-3004,Hospital Santa Sofía,Triage II,Pediatría,NaN,240000.0,19,Domicilio
4,ADM-3005,Hospital San Isidro,Triage II,Traumatología,60.0,800000.0,21,Observación
...,...,...,...,...,...,...,...,...
995,ADM-3996,Hospital Infantil,Triage IV,Medicina General,90.0,240000.0,48,Domicilio
996,ADM-3997,Hospital Infantil,Triage II,Medicina General,25.0,240000.0,11,Observación
997,ADM-3998,Hospital Santa Sofía,Triage IV,Cirugía,60.0,350000.0,76,Hospitalización
998,ADM-3999,Hospital San Isidro,Triage III,Medicina Interna,120.0,85000.0,30,Observación
999,ADM-4000,Hospital Infantil,Triage III,Cirugía,NaN,120000.0,4,Remisión

In [20]:
# Filtrado Booleano Simple
df_urgencias[df_urgencias["Edad_Paciente"] > 65]

,ID_Admision,Hospital,Nivel_Triage,Especialidad,Tiempo_Espera_Min,Costo_Procedimiento,Edad_Paciente,Destino_Alta
2,ADM-3003,Clínica San Marcel,Triage IV,Pediatría,60.0,120000.0,67,Domicilio
5,ADM-3006,Hospital San Isidro,Triage II,Traumatología,45.0,520000.0,72,Domicilio
17,ADM-3018,Clínica San Marcel,Triage IV,Traumatología,45.0,350000.0,73,Hospitalización
19,ADM-3020,Hospital San Isidro,Triage I,Pediatría,45.0,85000.0,89,Domicilio
26,ADM-3027,Hospital Infantil,Triage II,Pediatría,10.0,120000.0,88,Domicilio
...,...,...,...,...,...,...,...,...
1000,ADM-3041,Hospital Infantil,Triage I,Medicina Interna,25.0,85000.0,72,Domicilio
1001,ADM-3042,Hospital Infantil,Triage III,Pediatría,10.0,85000.0,80,Observación
1002,ADM-3043,Hospital Infantil,Triage III,Traumatología,10.0,240000.0,68,Observación
1004,ADM-3045,Hospital Infantil,Triage III,Pediatría,45.0,85000.0,73,Domicilio
1007,ADM-3048,Clínica San Marcel,Triage II,Pediatría,25.0,85000.0,71,Domicilio

In [21]:
# Filtrado Categórico por Lista (isin)
df_urgencias[df_urgencias["Hospital"].isin(["Hospital Santa Sofía", "Clínica San Marcel"])]

,ID_Admision,Hospital,Nivel_Triage,Especialidad,Tiempo_Espera_Min,Costo_Procedimiento,Edad_Paciente,Destino_Alta
2,ADM-3003,Clínica San Marcel,Triage IV,Pediatría,60.0,120000.0,67,Domicilio
3,ADM-3004,Hospital Santa Sofía,Triage II,Pediatría,NaN,240000.0,19,Domicilio
6,ADM-3007,Clínica San Marcel,Triage IV,Cirugía,45.0,85000.0,62,Remisión
8,ADM-3009,Clínica San Marcel,Triage II,Pediatría,90.0,85000.0,44,Hospitalización
10,ADM-3011,Hospital Santa Sofía,Triage II,Medicina General,60.0,85000.0,18,Observación
...,...,...,...,...,...,...,...,...
994,ADM-3995,Clínica San Marcel,Triage IV,Medicina Interna,90.0,240000.0,6,Domicilio
997,ADM-3998,Hospital Santa Sofía,Triage IV,Cirugía,60.0,350000.0,76,Hospitalización
1005,ADM-3046,Clínica San Marcel,Triage III,Pediatría,60.0,800000.0,21,Domicilio
1006,ADM-3047,Clínica San Marcel,Triage III,Cirugía,120.0,120000.0,57,Domicilio
1007,ADM-3048,Clínica San Marcel,Triage II,Pediatría,25.0,85000.0,71,Domicilio

In [22]:
# Filtrado por Intervalo Clínico (between)
df_urgencias[df_urgencias["Tiempo_Espera_Min"].between(30.0, 90.0)]

,ID_Admision,Hospital,Nivel_Triage,Especialidad,Tiempo_Espera_Min,Costo_Procedimiento,Edad_Paciente,Destino_Alta
0,ADM-3001,Hospital Infantil,Triage II,Medicina Interna,90.0,350000.0,29,Domicilio
1,ADM-3002,Hospital San Isidro,Triage II,Cirugía,45.0,NaN,9,Hospitalización
2,ADM-3003,Clínica San Marcel,Triage IV,Pediatría,60.0,120000.0,67,Domicilio
4,ADM-3005,Hospital San Isidro,Triage II,Traumatología,60.0,800000.0,21,Observación
5,ADM-3006,Hospital San Isidro,Triage II,Traumatología,45.0,520000.0,72,Domicilio
...,...,...,...,...,...,...,...,...
997,ADM-3998,Hospital Santa Sofía,Triage IV,Cirugía,60.0,350000.0,76,Hospitalización
1003,ADM-3044,Hospital San Marcos,Triage III,Pediatría,45.0,240000.0,5,Domicilio
1004,ADM-3045,Hospital Infantil,Triage III,Pediatría,45.0,85000.0,73,Domicilio
1005,ADM-3046,Clínica San Marcel,Triage III,Pediatría,60.0,800000.0,21,Domicilio
1008,ADM-3049,Hospital Infantil,Triage III,Pediatría,60.0,85000.0,50,Remisión

In [23]:
# Consultas Directas con .query()
df_urgencias.query("Nivel_Triage == 'Triage I' and Costo_Procedimiento > 300000")

,ID_Admision,Hospital,Nivel_Triage,Especialidad,Tiempo_Espera_Min,Costo_Procedimiento,Edad_Paciente,Destino_Alta
13,ADM-3014,Hospital Santa Sofía,Triage I,Medicina Interna,45.0,800000.0,62,Observación
109,ADM-3110,Hospital Infantil,Triage I,Pediatría,60.0,520000.0,16,Observación
117,ADM-3118,Hospital San Isidro,Triage I,Pediatría,45.0,800000.0,88,Domicilio
131,ADM-3132,Hospital San Isidro,Triage I,Pediatría,60.0,350000.0,54,Remisión
152,ADM-3153,Hospital Santa Sofía,Triage I,Cirugía,45.0,350000.0,67,Domicilio
178,ADM-3179,Hospital San Isidro,Triage I,Medicina Interna,90.0,350000.0,55,Observación
338,ADM-3339,Hospital Infantil,Triage I,Medicina General,10.0,520000.0,52,Domicilio
545,ADM-3546,Hospital San Isidro,Triage I,Traumatología,90.0,350000.0,34,Domicilio
610,ADM-3611,Hospital San Isidro,Triage I,Cirugía,45.0,350000.0,11,Domicilio
636,ADM-3637,Hospital Infantil,Triage I,Medicina Interna,60.0,350000.0,71,Remisión
743,ADM-3744,Clínica San Marcel,Triage I,Pediatría,NaN,520000.0,69,Observación
770,ADM-3771,Hospital Santa Sofía,Triage I,Medicina General,25.0,800000.0,6,Hospitalización
889,ADM-3890,Hospital San Marcos,Triage I,Traumatología,60.0,800000.0,82,Domicilio
911,ADM-3912,Hospital Infantil,Triage I,Medicina Interna,45.0,350000.0,14,Observación
984,ADM-3985,Clínica San Marcel,Triage I,Medicina General,NaN,520000.0,32,Domicilio
985,ADM-3986,Hospital San Isidro,Triage I,Cirugía,45.0,800000.0,4,Domicilio

In [81]:
# Filtrado Compuesto con Métodos de Texto
mascara = (df_urgencias["Destino_Alta"] == "Hospitalización") & (df_urgencias["Especialidad"].str.startswith("M"))
mascara

0       False
1       False
2       False
3       False
4       False
        ...
1005    False
1006    False
1007    False
1008    False
1009    False
Length: 1010, dtype: bool

In [117]:
# Imputación Estratificada de Faltantes
df_urgencias["Tiempo_Espera_Min"] = df_urgencias["Tiempo_Espera_Min"].fillna(df_urgencias["Tiempo_Espera_Min"].mean())
df_urgencias["Costo_Procedimiento"] = df_urgencias["Costo_Procedimiento"].fillna(0.0)
df_urgencias

,ID_Admision,Hospital,Nivel_Triage,Especialidad,Tiempo_Espera_Min,Costo_Procedimiento,Edad_Paciente,Destino_Alta
0,ADM-3001,Hospital Infantil,Triage II,Medicina Interna,90.000000,350000.0,29,Domicilio
1,ADM-3002,Hospital San Isidro,Triage II,Cirugía,45.000000,0.0,9,Hospitalización
2,ADM-3003,Clínica San Marcel,Triage IV,Pediatría,60.000000,120000.0,67,Domicilio
3,ADM-3004,Hospital Santa Sofía,Triage II,Pediatría,53.030623,240000.0,19,Domicilio
4,ADM-3005,Hospital San Isidro,Triage II,Traumatología,60.000000,800000.0,21,Observación
...,...,...,...,...,...,...,...,...
1005,ADM-3046,Clínica San Marcel,Triage III,Pediatría,60.000000,800000.0,21,Domicilio
1006,ADM-3047,Clínica San Marcel,Triage III,Cirugía,120.000000,120000.0,57,Domicilio
1007,ADM-3048,Clínica San Marcel,Triage II,Pediatría,25.000000,85000.0,71,Domicilio
1008,ADM-3049,Hospital Infantil,Triage III,Pediatría,60.000000,85000.0,50,Remisión
1009,ADM-3050,Hospital Infantil,Triage II,Cirugía,25.000000,240000.0,59,Domicilio

In [118]:
# Transformación Personalizada de Atributos (apply)
def clasificar(edad):
    if edad < 18:
        return "Pediatrico"
    elif edad <= 60:
        return "Adulta"
    else: 
        return "Adulto Mayor"

df_urgencias["Grupo_Etario"] = df_urgencias["Edad_Paciente"].apply(clasificar)
df_urgencias

,ID_Admision,Hospital,Nivel_Triage,Especialidad,Tiempo_Espera_Min,Costo_Procedimiento,Edad_Paciente,Destino_Alta,Grupo_Etario
0,ADM-3001,Hospital Infantil,Triage II,Medicina Interna,90.000000,350000.0,29,Domicilio,Adulta
1,ADM-3002,Hospital San Isidro,Triage II,Cirugía,45.000000,0.0,9,Hospitalización,Pediatrico
2,ADM-3003,Clínica San Marcel,Triage IV,Pediatría,60.000000,120000.0,67,Domicilio,Adulto Mayor
3,ADM-3004,Hospital Santa Sofía,Triage II,Pediatría,53.030623,240000.0,19,Domicilio,Adulta
4,ADM-3005,Hospital San Isidro,Triage II,Traumatología,60.000000,800000.0,21,Observación,Adulta
...,...,...,...,...,...,...,...,...,...
1005,ADM-3046,Clínica San Marcel,Triage III,Pediatría,60.000000,800000.0,21,Domicilio,Adulta
1006,ADM-3047,Clínica San Marcel,Triage III,Cirugía,120.000000,120000.0,57,Domicilio,Adulta
1007,ADM-3048,Clínica San Marcel,Triage II,Pediatría,25.000000,85000.0,71,Domicilio,Adulto Mayor
1008,ADM-3049,Hospital Infantil,Triage III,Pediatría,60.000000,85000.0,50,Remisión,Adulta
1009,ADM-3050,Hospital Infantil,Triage II,Cirugía,25.000000,240000.0,59,Domicilio,Adulta

In [112]:
# Renombrado y Reorganización de Campos
df_urgencias = df_urgencias.rename(columns={
    "Tiempo_Espera_Min":"Minutos_Espera",
    "Destino_Alta":"Egreso"
})

df_urgencias = df_urgencias[["Grupo_Etario"] + [c for c in df_urgencias.columns if c != "Grupo_Etario"]]
df_urgencias

,Grupo_Etario,ID_Admision,Hospital,Nivel_Triage,Especialidad,Minutos_Espera,Costo_Procedimiento,Edad_Paciente,Egreso
0,Adulta,ADM-3001,Hospital Infantil,Triage II,Medicina Interna,90.0,350000.0,29,Domicilio
1,Pediatrico,ADM-3002,Hospital San Isidro,Triage II,Cirugía,45.0,NaN,9,Hospitalización
2,Adulto Mayor,ADM-3003,Clínica San Marcel,Triage IV,Pediatría,60.0,120000.0,67,Domicilio
3,Adulta,ADM-3004,Hospital Santa Sofía,Triage II,Pediatría,NaN,240000.0,19,Domicilio
4,Adulta,ADM-3005,Hospital San Isidro,Triage II,Traumatología,60.0,800000.0,21,Observación
...,...,...,...,...,...,...,...,...,...
1005,Adulta,ADM-3046,Clínica San Marcel,Triage III,Pediatría,60.0,800000.0,21,Domicilio
1006,Adulta,ADM-3047,Clínica San Marcel,Triage III,Cirugía,120.0,120000.0,57,Domicilio
1007,Adulto Mayor,ADM-3048,Clínica San Marcel,Triage II,Pediatría,25.0,85000.0,71,Domicilio
1008,Adulta,ADM-3049,Hospital Infantil,Triage III,Pediatría,60.0,85000.0,50,Remisión
1009,Adulta,ADM-3050,Hospital Infantil,Triage II,Cirugía,25.0,240000.0,59,Domicilio

In [ ]:
# Agregación por Centro Hospitalario
df_urgencias.groupby("Hospital").agg(
    Promedio_Espera=("Minutos_Espera", "mean"),
    Costo_Total=("Costo_Procedimiento", "sum"),
)

                      Promedio_Espera  Costo_Total
Hospital
Clínica San Marcel          54.879808   48620000.0
Hospital Infantil           52.540107   49140000.0
Hospital San Isidro         52.172775   44515000.0
Hospital San Marcos         54.104938   34740000.0
Hospital Santa Sofía        51.507538   45160000.0

In [36]:
# Medición de Rango Clínico
def rango(series):
    return series.max() - series.min()

df_urgencias.groupby("Nivel_Triage")[["Minutos_Espera", "Costo_Procedimiento"]].agg(rango)

              Minutos_Espera  Costo_Procedimiento
Nivel_Triage
Triage I               170.0             715000.0
Triage II              170.0             715000.0
Triage III             170.0             715000.0
Triage IV              170.0             715000.0

In [38]:
# Agrupación Multinivel Avanzada
df_urgencias.groupby(["Hospital", "Nivel_Triage"]).agg(
    Edad_Promedio=("Edad_Paciente", "mean"),
    Costo_Total=("Costo_Procedimiento", "sum"),
)

                                   Edad_Promedio  Costo_Total
Hospital             Nivel_Triage
Clínica San Marcel   Triage I          40.434783    3660000.0
                     Triage II         44.714286   14135000.0
                     Triage III        42.484211   19785000.0
                     Triage IV         45.400000   11040000.0
Hospital Infantil    Triage I          47.818182    4170000.0
                     Triage II         40.966102   14345000.0
                     Triage III        46.597826   23350000.0
                     Triage IV         49.758621    7275000.0
Hospital San Isidro  Triage I          47.227273    4900000.0
                     Triage II         43.339286   13960000.0
                     Triage III        44.566667   18740000.0
                     Triage IV         48.205882    6915000.0
Hospital San Marcos  Triage I          61.400000    1790000.0
                     Triage II         46.517241   11140000.0
                     Triage III        34.575758   14245000.0
                     Triage IV         46.285714    7565000.0
Hospital Santa Sofía Triage I          54.411765    3850000.0
                     Triage II         43.765625   14130000.0
                     Triage III        45.515152   19305000.0
                     Triage IV         42.473684    7875000.0